// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC04zfDjFNzDAIYmi1XELwNu5p4v5aY1N4',
    appId: '1:421817940854:android:d04d7b9335d89ab169d857',
    messagingSenderId: '421817940854',
    projectId: 'habitconnect-e8fca',
    databaseURL: 'https://habitconnect-e8fca-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'habitconnect-e8fca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA78Xm_PcjluO2T3etWKW0h4bECfBLSKA',
    appId: '1:421817940854:ios:4af87a7cc0e4e88c69d857',
    messagingSenderId: '421817940854',
    projectId: 'habitconnect-e8fca',
    databaseURL: 'https://habitconnect-e8fca-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'habitconnect-e8fca.appspot.com',
    iosClientId: '421817940854-er27gme4df9305t4bq653jla03bg5pe1.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitConnectFlutter',
  );
}
